# Include any additional configuration file(s)
# [include] sections are processed in the order you write them
# Files in $CONFIG_DIR/topgrade.d/ are automatically included before this file
[include]
#paths = ["/etc/topgrade.toml"]

[misc]
# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["containers", "gnome_shell_extensions", "vim"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Sudo command to be used
#sudo_command = "sudo"

# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
#pre_sudo = false

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = [".cargo/bin/topgrade"]

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Display the time in step titles
#display_time = true

# Cleanup temporary or old files
cleanup = true

# Silence bug https://github.com/topgrade-rs/topgrade/issues/288
# Skip sending a notification at the end of a run
skip_notify = true

# Whether to self update (this is ignored if the binary has been built without self update support, available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
#no_self_update = true

# Extra Home Manager arguments
#home_manager_arguments = ["--flake", "file"]

[brew]
# I used to use --greedy.  I'm having problems upgrading Chrome and Firefox.
# => Remove --greedy, and let the browsers self-update.
#greedy_cask = true
#autoremove = true

# Custom commands
[commands]
"bash-completion for rustup" = "rustup completions bash > $(brew --prefix)/etc/bash_completion.d/rustup.bash-completion"
"bash-completion for cargo" = "rustup completions bash cargo >> ~/.local/share/bash-completion/completions/cargo"
"pip3 itself" = "pip3 install -U pip"
#"pip3 packages" = "pip3 freeze --local | cut -d = -f 1 | xargs -n1 pip3 install -U -q"
"pip3 packages" = "pip3 freeze --local | cut -d = -f 1 | cut -d ' ' -f 1 | xargs -n1 pip3 install -U -q"
"vim plugins" = "~/.vim/update_bundles.sh"
"pre-commit" = "cd ~/.config/git && pre-commit autoupdate && pre-commit install-hooks"

[composer]
#self_update = true

[distrobox]
#use_root = false
#containers = ["archlinux-latest"]

[firmware]
# Offer to update firmware; if false just check for and display available updates
#upgrade = true

[flatpak]
# Use sudo for updating the system-wide installation
#use_sudo = true

[git]
max_concurrency = 5
# Additional git repositories to pull
repos = [
    "~/yroyon-dotfiles/",
]

# Arguments to pass Git when pulling Repositories
pull_arguments = "--rebase --autostash --recurse-submodule=yes"

# Go
# NOTE: To update Go programs, topgrade needs 3rd party tool go-global-update
#       go install https://github.com/Gelio/go-global-update

[linux]
# Arch Package Manager to use. Allowed values: autodetect, aura, garuda_update, pacman, pamac, paru, pikaur, trizen, yay.
#arch_package_manager = "pacman"
# Arguments to pass yay (or paru) when updating packages
#yay_arguments = "--nodevel"
# Arguments to pass dnf when updating packages
#dnf_arguments = "--refresh"
#aura_aur_arguments = "-kx"
#aura_pacman_arguments = ""
#garuda_update_arguments = ""
#show_arch_news = true
#trizen_arguments = "--devel"
#pikaur_arguments = ""
#pamac_arguments = "--no-devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"
#redhat_distro_sync = false
#suse_dup = false
#rpm_ostree = false
#nix_arguments = "--flake"

[npm]
# Use sudo if the NPM directory isn't owned by the current user
#use_sudo = true

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Commands to run after anything
[post_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

[python]
#enable_pip_review = true                         ###disabled by default
#enable_pip_review_local = true                   ###disabled by default
#enable_pipupgrade = true                         ###disabled by default
#pipupgrade_arguments = "-y -u --pip-path pip"    ###disabled by default

[vagrant]
# Vagrant directories
#directories = []

# power on vagrant boxes if needed
#power_on = true

# Always suspend vagrant boxes instead of powering off
#always_suspend = true

[vim]
# For `vim-plug`, execute `PlugUpdate!` instead of `PlugUpdate`
#force_plug_update = true

[windows]
# Manually select Windows updates
#accept_all_updates = false
#open_remotes_in_new_terminal = true
#wsl_update_pre_release = true
#wsl_update_use_web_download = true

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop to Cargo
#self_rename = true

[yarn]
# Run `yarn global upgrade` with `sudo`
#use_sudo = true
