au BufRead,BufNewFile *.howto,howto,HOWTO    setfiletype asciidoc
au BufRead,BufNewFile *.readme,readme,README setfiletype asciidoc
au BufRead,BufNewFile *.todo,todo,TODO       setfiletype asciidoc
au BufRead,BufNewFile *.done                 setfiletype asciidoc
au BufRead,BufNewFile *.info                 setfiletype asciidoc
au BufRead,BufNewFile *.asciidoc             setfiletype asciidoc
au BufRead,BufNewFile *.adoc                 setfiletype asciidoc
"au BufRead,BufNewFile *.txt                  setfiletype asciidoc
au BufRead,BufNewFile *.credentials          setfiletype asciidoc
