---
# See https://pre-commit.com for more information
exclude: old/|previous/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace  # < 1s
      ## Conflicts with jsonlint style
      - id: end-of-file-fixer  # < 1s
      - id: check-added-large-files  # < 1s

  ## shell

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.2-1
    hooks:
      - id: shfmt  # < 1s
        args: [-s, -i, "4", -ci, -sr, -bn, -w]

  - repo: https://github.com/hadenlabs/pre-commit-hooks
    rev: 33801d5af598d97ee3c4cc017e54aa4a168f6287
    hooks:
      - id: shellcheck  # < 1s
        args: [-x, --shell=bash, --exclude=SC2002, --exclude=SC2164]
      # - id: terraform-fmt  # < 2s with recent TF, but VERY slow with our v0.14.11
      - id: terraform-tflint  # < 3s
      - id: terraform-tfsec  # < 2s

  ## config files

  ## Uses the python version.  Did not find a hook using the Rust version.
  #  - repo: https://github.com/sirosen/check-jsonschema
  #    rev: 0.10.2
  #    hooks:
  #      - id: check-jsonschema
  #        name: "Check GitHub Workflows"
  #        files: ^\.github/workflows/
  #        types: [yaml]
  #        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint  # < 4s
        args: [-c=.yamllint]
        exclude: "/templates/|.tmpl.yml|ansible/terraform/modules/app_portworx/manifests/portworx-etcd.yml|ansible/terraform/modules/app_portworx/manifests/portworx.yml"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint  # < 1s
        args: [--ignore, DL3008, --ignore, DL3013]
        # DL3003 DL3018

  ## python

  # No pycodestyle
  # No pyright
  # No ssort

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      # language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-six, types-PyYAML]

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D103,D212

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            -rn,
            # --rcfile=~/.config/pylintrc,
            --output-format=colorized,
            --fail-under=7,
          ]

