#!/bin/sh
set -e
mkdir .git/tags_lock 2>/dev/null
trap "rmdir .git/tags_lock; rm -f .git/tags.$$" EXIT

ctags --tag-relative -Rf .git/tags.$$ --exclude=.git --languages=-javascript,sql,css,html
mv .git/tags.$$ .git/tags
